# Generated by Django 3.2.4 on 2021-07-16 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(null=True, upload_to='products/images')),
                ('url', models.URLField(blank=True)),
                ('price', models.CharField(default='0', max_length=5)),
                ('storage_options', multiselectfield.db.fields.MultiSelectField(choices=[('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), (' ', ' ')], default=('64GB', '64GB'), max_length=24)),
                ('color_options', multiselectfield.db.fields.MultiSelectField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Matte-black', 'Matte-black'), ('Silver', 'Silver'), ('', '')], default=('Red', 'Red'), max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default=None, max_length=20)),
                ('storage', models.CharField(default=None, max_length=20)),
                ('order_date', models.DateTimeField(default=None)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
